name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    env:
      NODE_ENV: development
      BASE_URL: https://geoguessmaster.net/
      VUE_APP_API_KEY: VUE_APP_API_KEY
      VUE_APP_FIREBASE_API_KEY: VUE_APP_FIREBASE_API_KEY
      VUE_APP_FIREBASE_PROJECT_ID: VUE_APP_FIREBASE_PROJECT_ID
      VUE_APP_FIREBASE_MESSAGING_SENDER_ID: VUE_APP_FIREBASE_MESSAGING_SENDER_ID
      VUE_APP_FIREBASE_APP_ID: VUE_APP_FIREBASE_APP_ID
      VUE_APP_FIREBASE_MEASUREMENT_ID: VUE_APP_FIREBASE_MEASUREMENT_ID

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install CLI service
      run: npm install -g @vue/cli-service

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Run unit test
      run: npm run test:unit
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
